name: GetScreen Windows (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
ghghgh         cmd /c down.bat

      - name: Time Counter
        run: python time.py
